name: Node.js CI and Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4  # Checkout the repository to access the code
      
      - name: Use Node.js ${{ matrix.node-version }}  # Set up the specified Node version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}  # Use Node.js version from matrix
          cache: 'npm'  # Cache npm dependencies for faster builds

      - run: npm ci  # Install dependencies based on package-lock.json
      - run: npm run build --if-present  # Run build script if present in package.json
      - run: npm test  # Run tests as defined in package.json

      # Docker-related steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag github-actions:$(date +%s)

      - name: Push the Docker image
        run: |
          docker push github-actions:$(date +%s)

